name: 'Kestra Validate Action'
description: 'Validate a list of resources from a folder recursively'
branding:
  icon: 'check-circle'
  color: 'blue'
inputs:
  directory:
    description: 'Folder containing your resources'
    required: true
  resource:
    description: 'Resource you want to validate, can be "flow" or "template"'
    required: true
    type: choice
    options:
      - flow
      - template
  server:
    description: 'URL of your Kestra server, if none is provided, validation is done locally'
    required: false
  user:
    description: 'User for the basic auth'
    required: false
  password:
    description: 'Password for the basic auth'
    required: false
  apiToken:
    description: 'API Token (EE only)'
    required: false
  tenant:
    description: 'Tenant identifier (EE only, when multi-tenancy is enabled)'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.directory }}
    - ${{ inputs.resource }}
    - ${{ inputs.server }}
    - ${{ inputs.user }}
    - ${{ inputs.password }}
    - ${{ inputs.apiToken }}
    - ${{ inputs.tenant }}
